name: Get Git SHA
description: Get Git SHA value for deploy-ref

inputs:
  ref:
    default: main
    description: The branch, tag or SHA to make into a Docker image
    required: true

outputs:
  default-sha:
    description: commit sha for the default branch
    value: ${{ steps.default-sha.outputs.default-sha }}
  ref:
    description: The branch, tag or SHA
    value: ${{ inputs.ref }}
  sha:
    description: commit sha for the provided ref
    value: ${{ steps.sha.outputs.sha }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        ref: ${{ inputs.ref }}
    - name: Set Output sha
      id: sha
      run: |
        SHA=$(git rev-parse HEAD)
        if [ $SHA == "" ]
        then
          echo Ref ${{ inputs.ref }} not found in repo!
          exit 1
        fi
        echo "sha=${SHA}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Checkout ${{ github.event.repository.default_branch }}
      uses: actions/checkout@v3.5.0
      with:
        ref: ${{ github.event.repository.default_branch }}
    - name: Get sha of default branch
      id: default-sha
      run: |
        echo "default-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Show Outputs
      run: |
        echo ref: ${{ inputs.ref }}
        echo default-sha: ${{ steps.default-sha.outputs.default-sha }}
        echo sha: ${{ steps.sha.outputs.sha }}
      shell: bash
